# Generated by Django 5.0 on 2025-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=50, unique=True)),
                ('nbre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('id_producto', models.IntegerField(null=True)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('tel_cliente', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=50, unique=True)),
                ('nbre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.IntegerField(null=True)),
                ('sku_producto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField(unique=True)),
                ('nbre_producto', models.CharField(max_length=100)),
                ('nbre_cliente', models.CharField(max_length=100)),
                ('id_producto', models.IntegerField(null=True)),
                ('fecha_de_venta', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
